service: binary-test

package:
  exclude:
    - .DS_Store
    - .git/**
    - .idea/**
    - package.json
    - README.md
    - node_modules/chai/**
    - node_modules/mocha/**
    - node_modules/serverless/**
    - test/**

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: eu-west-1
  stage: dev

functions:
  fetchBinary:
    handler: binary/index.fetchBinary
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: fetchBinary
          method: GET

  fetchText:
    handler: text/index.fetchText
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: fetchText
          method: GET
