service: binary-test

package:
  individually: true
  exclude:
    - "**/*"

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs6.10
  profile: default
  region: eu-west-1
  stage: dev

functions:
  fetchBinary:
    handler: binary/index.fetchBinary
    package:
      include:
        - binary/sample.pdf
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: fetchBinary
          method: GET

  fetchText:
    handler: text/index.fetchText
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: fetchText
          method: GET
